# Generated by Django 4.1.7 on 2023-02-24 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_module', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'محصول', 'verbose_name_plural': 'محصولات'},
        ),
        migrations.AlterModelOptions(
            name='productcategory',
            options={'verbose_name': 'دسته بندی محصول', 'verbose_name_plural': 'دسته بندی های محصولات'},
        ),
        migrations.AddField(
            model_name='product',
            name='slug',
            field=models.SlugField(auto_created=True, default=1, unique=True, verbose_name='اسلاگ'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='tags',
            field=models.ManyToManyField(to='product_module.producttag', verbose_name='تگ های محصول'),
        ),
    ]
