# Generated by Django 4.1.7 on 2023-02-26 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact_module', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactus',
            name='date',
            field=models.DateTimeField(auto_created=True, auto_now_add=True, verbose_name='زمان ارسال'),
        ),
    ]
