# Generated by Django 4.1.7 on 2023-03-05 16:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(allow_unicode=True, auto_created=True, verbose_name='اسلاگ')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان مقاله')),
                ('short_description', models.TextField(verbose_name='خلاصه مقاله')),
                ('description', models.TextField(verbose_name='متن مقاله')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد مقاله')),
                ('view_counter', models.IntegerField(default=0, verbose_name='تعداد بازدیدها')),
                ('image', models.ImageField(upload_to='files/images/blogs', verbose_name='تصویر مقاله')),
                ('auther', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='نویسنده')),
            ],
            options={
                'verbose_name': 'مقاله',
                'verbose_name_plural': 'مقالات',
            },
        ),
        migrations.CreateModel(
            name='BlogCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان مقاله')),
                ('title_url', models.CharField(max_length=200, unique=True, verbose_name='عنوان در url')),
            ],
            options={
                'verbose_name': 'دسته بندی مقاله',
                'verbose_name_plural': 'دسته بندی های مقالات',
            },
        ),
        migrations.CreateModel(
            name='BlogTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان تگ')),
            ],
            options={
                'verbose_name': 'تگ مقاله',
                'verbose_name_plural': 'تگ های مقالات',
            },
        ),
        migrations.CreateModel(
            name='BlogComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(verbose_name='نمره')),
                ('comment', models.TextField(verbose_name='متن نظر')),
                ('blog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog_module.blog', verbose_name='مقاله')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'نظر',
                'verbose_name_plural': 'نظرها',
            },
        ),
        migrations.AddField(
            model_name='blog',
            name='blog_categories',
            field=models.ManyToManyField(to='blog_module.blogcategory', verbose_name='دسته بندی ها'),
        ),
        migrations.AddField(
            model_name='blog',
            name='tags',
            field=models.ManyToManyField(to='blog_module.blogtag', verbose_name='تگ ها'),
        ),
    ]
