# Generated by Django 4.1.7 on 2023-03-09 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog_module', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogcomment',
            old_name='comment',
            new_name='text',
        ),
    ]
