# Generated by Django 4.1.7 on 2023-03-09 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog_module', '0002_rename_comment_blogcomment_text'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogcomment',
            old_name='user',
            new_name='auther',
        ),
    ]
