# Generated by Django 4.1.7 on 2023-03-06 06:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog_module', '0002_remove_blogcomment_blog_remove_blogcomment_user_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(allow_unicode=True, auto_created=True, verbose_name='اسلاگ')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان مقاله')),
                ('title_in_url', models.CharField(max_length=300, verbose_name='عنوان مقاله در url')),
                ('short_description', models.TextField(verbose_name='خلاصه مقاله')),
                ('description', models.TextField(verbose_name='متن مقاله')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد مقاله')),
                ('view_counter', models.IntegerField(default=0, verbose_name='تعداد بازدیدها')),
                ('image', models.ImageField(upload_to='files/images/blogs', verbose_name='تصویر مقاله')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال / غیرفعال')),
                ('auther', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='نویسنده')),
                ('blog_categories', models.ManyToManyField(to='blog_module.blogcategory', verbose_name='دسته بندی ها')),
                ('tags', models.ManyToManyField(to='blog_module.blogtag', verbose_name='تگ ها')),
            ],
            options={
                'verbose_name': 'مقاله',
                'verbose_name_plural': 'مقالات',
            },
        ),
        migrations.CreateModel(
            name='BlogComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(verbose_name='نمره')),
                ('comment', models.TextField(verbose_name='متن نظر')),
                ('blog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog_module.blog', verbose_name='مقاله')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'نظر',
                'verbose_name_plural': 'نظرها',
            },
        ),
    ]
