# Generated by Django 4.1.7 on 2023-03-10 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_module', '0003_rename_user_blogcomment_auther'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogcomment',
            name='rating',
            field=models.IntegerField(null=True, verbose_name='نمره'),
        ),
    ]
