# Generated by Django 4.1.7 on 2023-03-06 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_module', '0004_alter_blog_auther'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='tags',
            field=models.ManyToManyField(blank=True, null=True, to='blog_module.blogtag', verbose_name='تگ ها'),
        ),
    ]
