# Generated by Django 4.1.7 on 2023-03-08 12:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog_module', '0005_alter_blog_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogcomment',
            name='replay',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='blog_module.blogcomment', verbose_name='ریپلای به'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='slug',
            field=models.SlugField(allow_unicode=True, auto_created=True, blank=True, verbose_name='اسلاگ'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='view_counter',
            field=models.IntegerField(default=0, editable=False, verbose_name='تعداد بازدیدها'),
        ),
    ]
