# Generated by Django 4.1.7 on 2023-03-08 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_module', '0006_blogcomment_replay_alter_blog_slug_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='tags',
            field=models.ManyToManyField(blank=True, to='blog_module.blogtag', verbose_name='تگ ها'),
        ),
    ]
