# Generated by Django 4.1.7 on 2023-03-05 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان')),
                ('description', models.TextField(verbose_name='توضیحات')),
                ('url_title', models.CharField(max_length=200, verbose_name='عنوان لینک')),
                ('url', models.URLField(max_length=500, verbose_name='لینک')),
                ('image', models.ImageField(upload_to='files/images/slider', verbose_name='تصویر')),
                ('is_active', models.BooleanField(default=True, verbose_name='قعال / غیرفعال')),
            ],
            options={
                'verbose_name': 'اسلایدر',
                'verbose_name_plural': 'اسلایدرها',
            },
        ),
    ]
