# Generated by Django 4.1.7 on 2023-03-05 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_module', '0002_footerlinkbox_footerlink'),
    ]

    operations = [
        migrations.AddField(
            model_name='footerlinkbox',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='فعال / غیر فعال بودن'),
        ),
    ]
