# Generated by Django 4.1.7 on 2023-03-02 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_module', '0002_remove_user_confirm_password'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'کاربر', 'verbose_name_plural': 'کاربران'},
        ),
        migrations.AddField(
            model_name='user',
            name='password_activation_code',
            field=models.CharField(max_length=100, null=True, verbose_name='کد فعال سازی رمز عبور'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email_activation_code',
            field=models.CharField(max_length=100, null=True, verbose_name='کد فعال سازی'),
        ),
    ]
