# Generated by Django 4.1.7 on 2023-03-09 13:48

from django.db import migrations, models
import pathlib


class Migration(migrations.Migration):

    dependencies = [
        ('account_module', '0004_user_about_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(default=pathlib.PureWindowsPath('C:/Users/MHMK/Desktop/Code/Django/eshop/files/images/user/profile-icon.png'), upload_to='files/images', verbose_name='پروفایل کاربر'),
        ),
    ]
