# Generated by Django 4.1.7 on 2023-03-10 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_module', '0005_alter_user_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(default='images/user/profile-icon.png', upload_to='files/images', verbose_name='پروفایل کاربر'),
        ),
    ]
